In [3]:
#1
import numpy as np
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']


In [4]:
#2
np.array([1,2,3])

array([1, 2, 3])

In [24]:
#3
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#4
Z=np.zeros((6,9))
print("%d bytes" %(Z.size*Z.itemsize))

432 bytes


In [7]:
#5
%run `python -c "import numpy; numpy.info(numpy.add)"`

Exception: File `'`python.py'` not found.

In [23]:
#6
Z=np.zeros(12)
Z[5]=1
print(Z)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [22]:
#7
np.arange(20,59)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

In [25]:
#8
Z=np.arange(21)
Z=Z[::-1]
print(Z)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [38]:
#9
my_list = [12,13,14,15,16,17,18,19,20]
np.array(my_list).reshape(3,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [39]:
#10
np.nonzero([3,7,0,0,9,0])

(array([0, 1, 4], dtype=int64),)

In [40]:
#11
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
#12
np.random.random((3,3,3))

array([[[0.96992716, 0.62021438, 0.4019529 ],
        [0.01556282, 0.8108002 , 0.61255013],
        [0.67664844, 0.81021283, 0.14097621]],

       [[0.9198398 , 0.87776798, 0.73135253],
        [0.58048489, 0.63373892, 0.25562472],
        [0.49948952, 0.12592326, 0.39318155]],

       [[0.34187124, 0.7833349 , 0.83628881],
        [0.89298037, 0.85232084, 0.81309519],
        [0.62336762, 0.24106103, 0.97701311]]])

In [58]:
#13
a=np.random.random((9,9))
print(a)
print(a.max())
print(a.min())

[[0.91619378 0.2382307  0.4307134  0.52162628 0.2633632  0.82154622
  0.02239185 0.55824964 0.32965129]
 [0.1457714  0.51024558 0.97581879 0.63785654 0.6846759  0.60419444
  0.35730451 0.65986941 0.00345704]
 [0.75817685 0.86964552 0.37696627 0.07661158 0.1669833  0.23568589
  0.26620696 0.52980826 0.89095627]
 [0.22338554 0.02057846 0.57895785 0.70364285 0.82029554 0.04161377
  0.5579192  0.774145   0.63858834]
 [0.02924759 0.68648155 0.2782833  0.53102569 0.76931122 0.2805655
  0.92514692 0.41481967 0.38293076]
 [0.03971865 0.99429381 0.62669654 0.95464207 0.02631919 0.75557925
  0.19962448 0.0554737  0.01680067]
 [0.58261459 0.65372781 0.70483193 0.61279868 0.22363638 0.89371123
  0.1640311  0.81803068 0.78416683]
 [0.26227329 0.77439954 0.23849114 0.2590742  0.14827592 0.96952378
  0.43186674 0.37324329 0.03211122]
 [0.27911826 0.87761214 0.72980526 0.8654671  0.22308632 0.74149194
  0.72224584 0.93353146 0.66337017]]
0.9942938118067051
0.0034570375913457463


In [50]:
#14
a=np.random.random(20)
a.mean()

0.6286959645012914

In [60]:
#15
a=np.ones((9,9))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [62]:
#16
a=np.ones((3,3))
a=np.pad(a,pad_width=1,mode='constant',constant_values=0)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [63]:
#17
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.7 == 7 * 0.1)

nan
False
False
nan
True
False


In [66]:
#18
a=np.diag(np.arange(1,6),k=-1)
print(a)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


In [68]:
#19
a=np.zeros((6,6),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
print(a)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


In [69]:
#20
np.unravel_index(100,(8,9,10))

(1, 1, 0)

In [71]:
#21
np.tile([[0,1],[1,0]],[4,4])

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [73]:
#22
a=np.random.random((6,6))
a=(a-np.mean(a))/(np.std(a))
print(a)

[[ 0.50355191  2.01797618 -1.03668701 -1.53317838  1.03132848  0.77147884]
 [-1.32686359 -1.58323234  0.12637073 -0.15775035  0.56624172 -1.43706179]
 [ 1.50257171  1.61946138 -1.11707367  0.11788     0.08449907  0.18167215]
 [-0.50429997  0.89562285 -0.201362   -1.09964715 -0.2602902   0.90096501]
 [ 0.71054864 -0.0367204  -0.98899775 -0.00300955 -0.44277562 -0.15644632]
 [ 0.28831949 -0.06304694  1.33292644 -1.40294819 -1.19051479  1.8904914 ]]


In [ ]:
#23


In [74]:
#24
a=np.ones((6,3))
b=np.ones((3,4))
np.dot(a,b)

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [76]:
#25
a=np.arange(1,10)
a[(a>3)&(a<8)]*=-1
print(a)

[ 1  2  3 -4 -5 -6 -7  8  9]


In [77]:
#26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [85]:
#27
a=np.array([1,2])
b=np.array([4,5])
print(a>b)
print(a>=b)
print(a<b)
print(a<=b)

[False False]
[False False]
[ True  True]
[ True  True]


In [86]:
#28
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-86-f3f98d8788e5>:2: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-86-f3f98d8788e5>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [91]:
#28
print(a**a)
print(a << a >> 2)
print(a <- a)
print(1j*a)
print(a/1/1)
print(a<a>a)

[1 4]
[0 2]
[False False]
[0.+1.j 0.+2.j]
[1. 2.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [93]:
#29
a=np.random.uniform(-4,+4,4)
print(np.copysign(np.ceil(np.abs(a)),a))

[ 2.  3. -3.  1.]


In [95]:
#30
a1=np.random.randint(0,9,5)
a2=np.random.randint(0,10,10)
print(np.intersect1d(a1,a2))

[0 2 4 5]


In [99]:
#31
defaults=np.seterr(all="ignore")
a=np.ones(1)/0
_=np.seterr(**defaults)
with np.errstate(divide='ignore'):
    a=np.ones(1)/0

In [100]:
#32
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [103]:
#33
yesterday=np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today=np.datetime64('today', 'D')
tomorrow=np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2022-04-20
2022-04-21
2022-04-22


In [104]:
#34
a=np.arange('2016-01', '2016-02', dtype='datetime64[D]')
print(a)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


In [117]:
#35
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
print(A)
print(B)
print(C)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

[1. 1. 1.]
[2. 2. 2.]
[3. 3. 3.]


array([-1.5, -1.5, -1.5])

In [120]:
#36
a=np.random.uniform(0,10,7)
print(a-a%1)
print(np.floor(a))
print(a.astype(int))
print(np.trunc(a))

[0. 1. 5. 2. 7. 5. 4.]
[0. 1. 5. 2. 7. 5. 4.]
[0 1 5 2 7 5 4]
[0. 1. 5. 2. 7. 5. 4.]


In [122]:
#37
a=np.zeros((3,3))
a += np.arange(3)
print(a)

[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


In [123]:
#38
def generate():
    for x in range(9):
        yield x
a=np.fromiter(generate(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


In [124]:
#39
a=np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [125]:
#40
a=np.random.random(10)
a.sort()
print(a)

[0.10951882 0.15720565 0.30468927 0.44312483 0.45376657 0.53257638
 0.6745126  0.87441381 0.89262118 0.98296976]


In [126]:
#41
a=np.arange(9)
np.add.reduce(a)

36

In [127]:
#42
A=np.random.randint(0,7,5)
B=np.random.randint(0,7,5)
equal=np.allclose(A,B)
print(equal)
equal=np.array_equal(A,B)
print(equal)

False
False


In [129]:
#43
a=np.zeros(9)
a.flags.writeable=False
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [130]:
#44
a=np.random.random((5,2))
X,Y=a[:,0], a[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)

[0.99600005 0.63879041 0.33740254 0.8018171  0.56618984]
[1.09545863 0.31168874 1.56379789 0.63204595 1.45403454]


In [132]:
#45
a=np.random.random(5)
a[a.argmax()]=0
print(a)

[0.         0.794143   0.08364094 0.05824598 0.69354412]


In [136]:
#46
a=np.zeros((3,3), [('x',float),('y',float)])
a['x'],a['y'] = np.meshgrid(np.linspace(0,1,3), np.linspace(0,1,3))
print(a)

[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


In [137]:
#47
X = np.arange(6)
Y = X + 0.5
C = 1.0/np.subtract.outer(X,Y)
print(np.linalg.det(C))

396.03682955582303


In [138]:
#48
for dtype in [np.int8,np.int32,np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [143]:
#49
a=np.zeros((5,5))
np.set_printoptions
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [144]:
#50
Z=np.arange(100)
v=np.random.uniform(0,100)
index=(np.abs(Z-v)).argmin()
print(Z[index])

91


In [147]:
#51
a=np.zeros(6,[('position',[('x',float,1),
                                  ('y',float,1)]),
              ('color',   [('r',float,1),
                                  ('g',float,1),
                                  ('b',float,1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-147-0543cb56f8aa>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a=np.zeros(6,[('position',[('x',float,1),


In [33]:
#52
Z=np.random.random((10,2))
X,Y=np.atleast_2d(Z[:,0], Z[:,1])
D=np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.12424433 0.3760532  0.84332137 0.40299377 0.77742618
  0.5928634  0.73408499 0.83795986 0.65955705]
 [0.12424433 0.         0.44261199 0.96656245 0.51084735 0.89441486
  0.69358822 0.85134081 0.96213126 0.78361097]
 [0.3760532  0.44261199 0.         0.81744762 0.59348203 0.84245188
  0.77757983 0.80200782 0.747907   0.62982592]
 [0.84332137 0.96656245 0.81744762 0.         0.51297495 0.19959991
  0.45746588 0.20953883 0.14526801 0.19226618]
 [0.40299377 0.51084735 0.59348203 0.51297495 0.         0.39445428
  0.19521929 0.35338122 0.56405159 0.37292296]
 [0.77742618 0.89441486 0.84245188 0.19959991 0.39445428 0.
  0.28182389 0.04353718 0.33112345 0.249957  ]
 [0.5928634  0.69358822 0.77757983 0.45746588 0.19521929 0.28182389
  0.         0.25349828 0.55445652 0.38968903]
 [0.73408499 0.85134081 0.80200782 0.20953883 0.35338122 0.04353718
  0.25349828 0.         0.32897154 0.22324018]
 [0.83795986 0.96213126 0.747907   0.14526801 0.56405159 0.33112345
  0.55445652 0.32897

In [151]:
#53
a=np.arange(21,dtype=np.float32)
a=a.astype(np.int32, copy=False)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [6]:
#54
import numpy as np
from io import StringIO
s=StringIO("""1, 2, 3, 4, 5\n
              6,  ,  , 7, 8\n
               ,  , 9,10,11\n""")
a=np.genfromtxt(s,delimiter=",",dtype=np.int)
print(a)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-6-de28366c81d4>:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.genfromtxt(s,delimiter=",",dtype=np.int)


In [10]:
#55
a=np.arange(4).reshape(2,2)
for index,value in np.ndenumerate(a):
    print(index,value)
for index in np.ndindex(a.shape):
    print(index,a[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


In [13]:
#56
X,Y=np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma,mu=1.0,0.0
G=np.exp(-((D-mu)**2/(2.0*sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [5]:
#57
import numpy as np
n=6
e=9
a=np.zeros((n,n))
np.put(a,np.random.choice(range(n*n),e,replace=False),1)
print(a)

[[0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0.]]


In [7]:
#58
X=np.random.rand(5,5)
Y=X-X.mean(axis=1,keepdims=True)
Y=X-X.mean(axis=1).reshape(-1,1)
print(Y)

[[-0.15166144  0.22053074 -0.01959001 -0.25669687  0.20741758]
 [-0.18576361  0.05142511 -0.22727529 -0.09884205  0.46045582]
 [ 0.19081914  0.44146616 -0.16727083 -0.17645462 -0.28855985]
 [ 0.27221312  0.15350587 -0.41898033 -0.08045211  0.07371344]
 [ 0.11105082  0.2920225  -0.42523448  0.43555612 -0.41339495]]


In [10]:
#59
a=np.random.randint(0,9,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[7 2 7]
 [1 0 1]
 [2 4 0]]
[[1 0 1]
 [7 2 7]
 [2 4 0]]


In [13]:
#60
a=np.random.randint(0,7,(3,5))
print((~a.any(axis=0)).any())

False


In [15]:
#61
A=np.random.uniform(0,1,9)
a=0.5
m=A.flat[np.abs(A-a).argmin()]
print(m)

0.522850556422883


In [16]:
#62
A=np.arange(3).reshape(3,1)
B=np.arange(3).reshape(1,3)
it=np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [18]:
#63
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
 
a=NamedArray(np.arange(21), "range_21")
print(a.name)

range_21


In [21]:
#64
a=np.ones(9)
I=np.random.randint(0,len(a),7)
a +=np.bincount(I,minlength=len(a))
print(a)
np.add.at(a, I, 1)
print(a)

[3. 1. 3. 1. 1. 2. 2. 1. 2.]
[5. 1. 5. 1. 1. 3. 3. 1. 3.]


In [23]:
#65
X = [1,2,3,4,5,6]
I = [1,3,7,11,2,1]
F = np.bincount(I,X)
print(F)

[0. 7. 5. 2. 0. 0. 0. 3. 0. 0. 0. 4.]


In [27]:
#66
w,h = 7,7
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


In [30]:
#67
A = np.random.randint(0,6,(2,3,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[36 28 40]
 [21 33 29]]
[[36 28 40]
 [21 33 29]]


In [32]:
#68
D = np.random.uniform(0,1,50)
S = np.random.randint(0,10,50)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.32346316 0.76090611 0.565437   0.34095791 0.31861756 0.60689744
 0.40640629 0.44228721 0.54550709 0.37001264]


In [34]:
#69
A=np.random.uniform(0,1,(3,3))
B=np.random.uniform(0,1,(3,3))
np.diag(np.dot(A,B))

array([0.75956858, 0.65122749, 1.28478851])

In [35]:
#70
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [36]:
#71
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [38]:
#72
a=np.arange(16).reshape(4,4)
a[[0,1]]=a[[1,0]]
print(a)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


In [39]:
#73
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 5, 83) ( 5, 95) ( 7, 16) ( 7, 93) ( 8, 50) ( 8, 80) ( 8, 92) ( 8, 93)
 (12, 53) (12, 58) (16, 93) (17, 59) (17, 71) (21, 50) (21, 53) (42, 59)
 (42, 66) (50, 53) (50, 80) (52, 67) (52, 85) (53, 58) (59, 66) (59, 71)
 (67, 85) (68, 85) (68, 88) (83, 95) (85, 88) (92, 93)]


In [40]:
#74
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [43]:
#75
def moving_average(a,n=2):
    ret=np.cumsum(a,dtype=float)
    ret[n:]=ret[n:]-ret[:-n]
    return ret[n-1:]/n
Z=np.arange(10)
print(moving_average(Z,n=3))

[1. 2. 3. 4. 5. 6. 7. 8.]


In [46]:
#76
from numpy.lib import stride_tricks
 
def rolling(a,window):
    shape=(a.size-window+1,window)
    strides=(a.itemsize,a.itemsize)
    return stride_tricks.as_strided(a,shape=shape,strides=strides)
Z = rolling(np.arange(8), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


In [51]:
#77
Z = np.random.randint(0,2,20)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,20)
np.negative(Z, out=Z)

array([ 0.46635947,  0.18950652, -0.67756312, -0.49761852, -0.67347606,
       -0.44470611,  0.21705122, -0.3458333 , -0.43267078, -0.83053967,
        0.41035265, -0.91799062,  0.08627198, -0.64142721, -0.56017523,
       -0.3896434 , -0.1133987 ,  0.07755076,  0.78051045,  0.92079367])

In [54]:
#78

def distance(P0, P1, p):
    T=P1-P0
    L=(T**2).sum(axis=1)
    U=-((P0[:,0]-p[...,0])*T[:,0]+(P0[:,1]-p[...,1])*T[:,1])/L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
 
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,(1,2))
print(distance(P0, P1, p))

[ 3.42954294  4.17355052  3.26333168  0.88091312  9.28784352  4.2633146
  5.30542969  5.47769066 17.12676568  6.19442664]


In [58]:
#79
P0 =np.random.uniform(-10,10,(10,2))
P1 =np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(5,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[11.0825454  10.52771164  5.08408517  4.57764855  5.52829104  8.6502615
   4.0927917   0.64220334 11.84593143 12.49373471]
 [13.49392677  1.78508141  2.71776501  8.59488974  7.68239528  2.18522931
   0.93697937  8.79854447  2.48773216  0.37176538]
 [22.35820446  2.2357538  13.03045079 16.6947093   1.31743103  6.99294148
  11.37107692 12.97367787 12.39566886  0.3110457 ]
 [15.42013315  9.18063041  9.65248523  8.70878464  7.26200618 11.90935186
   8.64458971  2.16832986 15.58029776 11.62173104]
 [10.04682781  0.07777906  0.57661394  5.19396553  8.08898556  3.90868128
   2.2907443   6.02520161  0.30345979  1.16951506]]


In [60]:
#80
a=np.random.randint(0,10,(8,8))
shape=(5,5)
fill=0
position=(1,1)


In [63]:
#81
Z=np.arange(1,15,dtype=np.uint32)
R=stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [65]:
#82
Z = np.random.uniform(0,1,(9,9))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

9


In [67]:
#83
Z = np.random.randint(0,10,10)
print(np.bincount(Z).argmax())

5


In [68]:
#84
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C=stride_tricks.as_strided(Z,shape=(i,j,n,n),strides=Z.strides+Z.strides)
print(C)

[[[[4 3 4]
   [2 1 1]
   [3 4 0]]

  [[3 4 2]
   [1 1 3]
   [4 0 1]]

  [[4 2 0]
   [1 3 3]
   [0 1 4]]

  [[2 0 2]
   [3 3 2]
   [1 4 3]]

  [[0 2 0]
   [3 2 2]
   [4 3 2]]

  [[2 0 3]
   [2 2 2]
   [3 2 2]]

  [[0 3 2]
   [2 2 1]
   [2 2 2]]

  [[3 2 1]
   [2 1 2]
   [2 2 0]]]


 [[[2 1 1]
   [3 4 0]
   [2 2 1]]

  [[1 1 3]
   [4 0 1]
   [2 1 1]]

  [[1 3 3]
   [0 1 4]
   [1 1 4]]

  [[3 3 2]
   [1 4 3]
   [1 4 3]]

  [[3 2 2]
   [4 3 2]
   [4 3 2]]

  [[2 2 2]
   [3 2 2]
   [3 2 1]]

  [[2 2 1]
   [2 2 2]
   [2 1 0]]

  [[2 1 2]
   [2 2 0]
   [1 0 2]]]


 [[[3 4 0]
   [2 2 1]
   [0 2 0]]

  [[4 0 1]
   [2 1 1]
   [2 0 4]]

  [[0 1 4]
   [1 1 4]
   [0 4 4]]

  [[1 4 3]
   [1 4 3]
   [4 4 3]]

  [[4 3 2]
   [4 3 2]
   [4 3 0]]

  [[3 2 2]
   [3 2 1]
   [3 0 4]]

  [[2 2 2]
   [2 1 0]
   [0 4 1]]

  [[2 2 0]
   [1 0 2]
   [4 1 1]]]


 [[[2 2 1]
   [0 2 0]
   [4 3 0]]

  [[2 1 1]
   [2 0 4]
   [3 0 2]]

  [[1 1 4]
   [0 4 4]
   [0 2 3]]

  [[1 4 3]
   [4 4 3]
   [2 3 2]]

  [[4 3 2]
   

In [69]:
#85
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
 
def symetric(a):
    return np.asarray(a+a.T-np.diag(a.diagonal())).view(Symetric)
 
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3]=42
print(S)

[[ 2  8  1  8 10]
 [ 8  5  9 10 18]
 [ 1  9  1 42  8]
 [ 8 10 42  1 12]
 [10 18  8 12  2]]


In [72]:
#86
p, n = 10,10
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M,V,axes=[[0,2],[0,1]])
print(S)

[[100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]]


In [73]:
#87
Z = np.ones((16,16))
k = 4
S=np.add.reduceat(np.add.reduceat(Z,np.arange(0,Z.shape[0],k),axis=0),
                                    np.arange(0,Z.shape[1],k),axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [74]:
#88


In [77]:
#89
Z = np.arange(100)
np.random.shuffle(Z)
n=6
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[94 95 96 97 98 99]
[95 99 98 96 97 94]


In [80]:
#90
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1,2,3],[2,3],[7,8])))

[[1 2 7]
 [1 2 8]
 [1 3 7]
 [1 3 8]
 [2 2 7]
 [2 2 8]
 [2 3 7]
 [2 3 8]
 [3 2 7]
 [3 2 8]
 [3 3 7]
 [3 3 8]]


In [87]:
#91
Z=np.array([("green",7.9,3),
            ("love",5.8,2)])
R=np.core.records.fromarrays(Z.T,
                               names='col1,col2,col3',
                               formats='S8,f8,i8')
print(R)

[(b'green', 7.9, 3) (b'love', 5.8, 2)]


In [90]:
#92
Z=np.random.rand(int(5e7))
%timeit np.power(Z,3)
%timeit Z*Z*Z
%timeit np.einsum('i,i,i->i',Z,Z,Z)

4.26 s ± 669 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
575 ms ± 60.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
253 ms ± 29.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
[0.33117938 0.8298842  0.42684891 ... 0.18530719 0.15583968 0.11971831]


In [94]:
#93
A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))
C=(A[..., np.newaxis,np.newaxis]==B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 7]


In [95]:
#94
Z = np.random.randint(0,5,(10,3))
print(Z)

[[3 3 3]
 [1 1 3]
 [2 2 4]
 [1 0 2]
 [0 0 3]
 [0 2 0]
 [3 2 4]
 [2 1 0]
 [2 0 2]
 [3 2 0]]


In [96]:
#95
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [99]:
#96
Z=np.random.randint(0,2,(3,3))
T=np.ascontiguousarray(Z).view(np.dtype((np.void,Z.dtype.itemsize * Z.shape[1])))
_,idx=np.unique(T,return_index=True)
uZ=Z[idx]
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 0]]


In [103]:
#97
A = np.random.uniform(0,1,3)
B = np.random.uniform(0,1,3)
np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.09179876, 0.06707651, 0.02985358],
       [0.24436983, 0.17855879, 0.07947074],
       [0.38704356, 0.28280917, 0.12586921]])

In [104]:
#98


In [107]:
#99
X=np.asarray([[1.0, 0.0, 3.0, 9.0],
              [2.0, 0.0, 1.0, 1.0],
              [1.5, 2.5, 1.0, 0.0]])
n=4
M=np.logical_and.reduce(np.mod(X,1)==0,axis=-1)
M &=(X.sum(axis=-1)==n)
print(X[M])

[[2. 0. 1. 1.]]


In [112]:
#100
X = np.random.randn(100) 
N = 1000
idx = np.random.randint(0, X.size,(N,X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means,[2.5,97.5])
print(confint)

[-0.18375067  0.16036604]
